#!/usr/bin/env bash
# Script para verificar el estado del servidor cuando SSH no funciona

SERVER="165.227.69.58"

echo "╔════════════════════════════════════════════════════════════╗"
echo "║     DIAGNÓSTICO DEL SERVIDOR - NO HAY ACCESO SSH          ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "🔍 Servidor: $SERVER"
echo ""

# 1. Verificar si el servidor está UP (ping)
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1️⃣  VERIFICANDO SI EL SERVIDOR ESTÁ ENCENDIDO (PING)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
if ping -c 3 -W 5 $SERVER > /dev/null 2>&1; then
    echo "✅ El servidor responde a PING - está ENCENDIDO"
else
    echo "❌ El servidor NO responde a PING"
    echo "   Posibles causas:"
    echo "   - El servidor está apagado en DigitalOcean"
    echo "   - Problema de red"
    echo ""
    echo "👉 SOLUCIÓN: Entra al panel de DigitalOcean y verifica que el droplet esté encendido"
fi
echo ""

# 2. Verificar puerto SSH (22)
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "2️⃣  VERIFICANDO PUERTO SSH (22)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
if nc -z -w 5 $SERVER 22 2>/dev/null; then
    echo "✅ Puerto SSH (22) está ABIERTO pero la autenticación falla"
    echo "   Posibles causas:"
    echo "   - Cambió la clave SSH"
    echo "   - Cambió la configuración del servidor"
else
    echo "❌ Puerto SSH (22) está CERRADO o bloqueado"
    echo "   Posibles causas:"
    echo "   - El firewall está bloqueando el puerto"
    echo "   - La VPN está interfiriendo con SSH"
    echo "   - El servicio SSH está caído"
fi
echo ""

# 3. Información para el usuario
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "3️⃣  SOLUCIONES DISPONIBLES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📌 OPCIÓN A: Usar la Consola Web de DigitalOcean"
echo "   1. Ve a: https://cloud.digitalocean.com/"
echo "   2. Busca tu droplet (IP: $SERVER)"
echo "   3. Haz clic en 'Console' o 'Access Console'"
echo "   4. Una vez dentro, ejecuta:"
echo ""
echo "      # Ver estado del bot"
echo "      systemctl status dragonbot"
echo ""
echo "      # Ver logs recientes"
echo "      journalctl -u dragonbot -n 50"
echo ""
echo "      # Ver logs en tiempo real"
echo "      journalctl -u dragonbot -f"
echo ""
echo "      # Reiniciar el bot"
echo "      systemctl restart dragonbot"
echo ""
echo "      # Ver IP actual (para verificar VPN)"
echo "      curl ifconfig.me"
echo ""
echo "────────────────────────────────────────────────────────────"
echo ""
echo "📌 OPCIÓN B: Verificar en el Panel de DigitalOcean"
echo "   1. Ve a: https://cloud.digitalocean.com/"
echo "   2. Verifica que el droplet esté 'ON' (encendido)"
echo "   3. Revisa gráficas de CPU/Memoria"
echo "   4. Revisa si hay alertas del sistema"
echo ""
echo "────────────────────────────────────────────────────────────"
echo ""
echo "📌 OPCIÓN C: Reiniciar el droplet desde el panel"
echo "   1. Ve a: https://cloud.digitalocean.com/"
echo "   2. Encuentra tu droplet"
echo "   3. Haz clic en 'Power' → 'Reboot'"
echo "   4. Espera 2-3 minutos y prueba de nuevo la conexión SSH"
echo ""
echo "────────────────────────────────────────────────────────────"
echo ""
echo "📌 OPCIÓN D: Verificar el bot via Telegram"
echo "   - El bot debe estar enviando mensajes a Telegram"
echo "   - Revisa tu chat de Telegram con el bot"
echo "   - Si hay mensajes recientes, el bot está funcionando"
echo "   - Si no hay mensajes, el bot puede estar caído"
echo ""
echo "────────────────────────────────────────────────────────────"
echo ""
echo "⚠️  NOTAS IMPORTANTES:"
echo "   - La VPN puede estar bloqueando el puerto SSH"
echo "   - Si el bot funciona (envía mensajes a Telegram), NO es urgente el SSH"
echo "   - Puedes usar la consola web de DigitalOcean en lugar de SSH"
echo ""
