#!/usr/bin/env bash
# Script interactivo para diagnosticar el servidor
# Este script te guiará paso a paso

SERVER="165.232.142.48"
USER="root"

echo "╔════════════════════════════════════════════════════════════╗"
echo "║     DIAGNÓSTICO INTERACTIVO - DRAGON BOT                   ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "Este script intentará conectarse a: $USER@$SERVER"
echo ""

# Probar conexión básica
echo "🔍 Probando conexión SSH..."
if ssh -o ConnectTimeout=10 -o StrictHostKeyChecking=no $USER@$SERVER 'echo "Conexión exitosa"' 2>/dev/null; then
    echo "✅ Conexión SSH funciona correctamente"
    echo ""
    
    # Si la conexión funciona, ejecutar diagnóstico completo
    echo "Ejecutando diagnóstico completo..."
    bash "$(dirname "$0")/diagnose_server.sh"
else
    echo "❌ No se puede conectar al servidor"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "OPCIONES PARA CONECTARTE:"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "Opción 1: Conectarte manualmente y ejecutar comandos"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "Abre una terminal y ejecuta:"
    echo ""
    echo "  ssh root@165.232.142.48"
    echo ""
    echo "Luego ejecuta estos comandos uno por uno:"
    echo ""
    echo "# 1. Ver estado del bot"
    echo "systemctl status dragonbot"
    echo ""
    echo "# 2. Ver logs recientes"
    echo "journalctl -u dragonbot -n 50 --no-pager"
    echo ""
    echo "# 3. Ver errores"
    echo "journalctl -u dragonbot -n 100 --no-pager | grep -i error"
    echo ""
    echo "# 4. Verificar PostgreSQL"
    echo "systemctl status postgresql"
    echo ""
    echo "# 5. Verificar archivos críticos"
    echo "ls -lh /root/EVOLUTION-SCRAPER/storage_state.json"
    echo "ls -lh /root/EVOLUTION-SCRAPER/.env"
    echo ""
    echo "# 6. Verificar IP (debe ser de Colombia si usas VPN)"
    echo "curl ifconfig.me"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "Opción 2: Configurar llave SSH (recomendado)"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "Si no tienes llave SSH configurada, créala con:"
    echo ""
    echo "  ssh-keygen -t ed25519 -C 'tu@email.com'"
    echo "  ssh-copy-id root@165.232.142.48"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "Opción 3: Usar el panel web de DigitalOcean"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "1. Ve a: https://cloud.digitalocean.com/droplets"
    echo "2. Busca tu droplet (IP: 165.232.142.48)"
    echo "3. Click en 'Console' o 'Access'"
    echo "4. Ejecuta los comandos mostrados arriba"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "SOLUCIONES RÁPIDAS COMUNES:"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "Si el bot está caído, reiniciarlo:"
    echo "  ssh root@165.232.142.48 'systemctl restart dragonbot'"
    echo ""
    echo "Si la sesión del casino expiró:"
    echo "  1. En tu Mac (con VPN Colombia):"
    echo "     cd /Users/miguelantonio/Desktop/EVOLUTION-SCRAPER"
    echo "     source venv/bin/activate"
    echo "     python save_storage_state.py"
    echo "  2. Cuando estés en la mesa, en otra terminal:"
    echo "     touch storage_state.ready"
    echo "  3. Subir al servidor:"
    echo "     scp storage_state.json root@165.232.142.48:/root/EVOLUTION-SCRAPER/"
    echo "  4. Reiniciar bot:"
    echo "     ssh root@165.232.142.48 'systemctl restart dragonbot'"
    echo ""
fi
